{
    'name': 'Tmtr_exchange',
    'category': 'Technical',
    'depends': [
        'base',
        'web',
        'mail',
        'tms',
        'base_odata_1c',
    ],
    'data': [
        'security/ir.model.access.csv',
        'report/efficiency_saler_view.xml',
        'report/efficiency_saler_history_view.xml',
        'report/efficiency_report_template.xml',
        'report/best_one_report_template.xml',
        'report/debts_report_template.xml',
        'views/tmtr_exchange_contact.xml',
        'views/tmtr_exchange_user.xml',
        'views/tmtr_exchange_partner.xml',
        'views/tmtr_exchange_business_type.xml',
        'views/tmtr_exchange_business_region.xml',
        'views/tmtr_exchange_department.xml',
        'views/tmtr_exchange_type.xml',
        'views/tmtr_exchange_counterparty.xml',
        'views/tmtr_exchange_sales.xml',
        'views/tms_route_view.xml',
        'views/tmtr_exchange_indicatiors.xml',
        'views/tmtr_exchange_interaction.xml',
        'views/tmtr_exchange_order.xml',
        'views/tmtr_exchange_route.xml',
        'views/tmtr_exchange_implemention.xml',
        'views/res_config_settings_views.xml',
        'views/tmtr_exchange_menu_views.xml',
        'views/tmtr_exchange_report.xml',
    ],
    'installable': True,
    'application': True,
}